# Generated by Django 3.0.3 on 2020-04-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Class', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
